### ISSUE TITLE
Order of injection

### ISSUE THREAD

**Issue by cephasteom** [me4502/gatsby-plugin-react-helmet-async#80] opened 2021-10-29 11:22 UTC
Hi all,

Thanks for a great plugin. Makes putting things in the head a breeze.

I'm using this plugin to add in SEO items. The problem is, these appear below the inline css, so many social media providers stop reading halfway through the css and the social cards don't get rendered.

Is it possible to specify where the meta tags get rendered - ie, can you say, put the items at the top of the head?

Many thanks,

Pete.

**Comment by textpain** [comment] 2022-03-08 10:06
Hi Pete, this might be useful: https://github.com/staylor/react-helmet-async#prioritizing-tags-for-seo

**Comment by Undistraction** [comment] 2022-05-25 13:34
The problem is that this isn't supported by this plugin. For this to work, it needs to implement `helmet.priority.toString()` in `gatsby-ssr.js` [here](https://github.com/Collabsalot/gatsby-plugin-react-helmet-async/blob/9b30014757151ac9e18c6e29a7f58d9d85e435a2/gatsby-ssr.js#L14). :

```
helmet.base.toComponent(),
helmet.title.toComponent(),
helmet.priority.toString(),
helmet.meta.toComponent(),
helmet.link.toComponent(),
helmet.style.toComponent(),
helmet.script.toComponent(),
helmet.noscript.toComponent(),
```

Guess it should probably be added conditionally based on a config variable.

**Comment by me4502** [comment] 2022-06-13 10:23
> The problem is that this isn't supported by this plugin. For this to work, it needs to implement `helmet.priority.toString()` in `gatsby-ssr.js` [here](https://github.com/Collabsalot/gatsby-plugin-react-helmet-async/blob/9b30014757151ac9e18c6e29a7f58d9d85e435a2/gatsby-ssr.js#L14). :
> 
> ```
> helmet.base.toComponent(),
> helmet.title.toComponent(),
> helmet.priority.toString(),
> helmet.meta.toComponent(),
> helmet.link.toComponent(),
> helmet.style.toComponent(),
> helmet.script.toComponent(),
> helmet.noscript.toComponent(),
> ```
> 
> Guess it should probably be added conditionally based on a config variable.

This has been resolved in https://github.com/me4502/gatsby-plugin-react-helmet-async/commit/be98a85250191c22ee6d2b2ebb457b542abb01e5

Unless there was something else wrong here, I'll close this issue. I'll try to get the above commit into a release shortly.

**Closed as completed by me4502** 2022-06-13 10:23 UTC
